### ISSUE TITLE
Index configuration

### ISSUE THREAD

**Issue by elv-zenia** [eluv-io/elv-fabric-browser#32]
Create a new page for managing index fields with an additional way to update search index.

Index settings

- site object (root)  - a picker for an object

```
fabric:
  root:
    content:
        "iq__3eJ4QHB7R8wmmvhp4Hz7eqRZfzg"
     library:
        "ilib2XX6yS9S8bgAeLVxDGKeoNcNVckN"
```

- document prefix   (text)      default `/`

```
indexer:
    arguments:
        document:
            prefix:
                "/assets/*"
```

- query suffix  (a term that is always added to the end of all queries)
  - maybe 'static query terms'

```
indexer:
    arguments:
        query:
             suffix:
                   "AND (-f_original_access:[100 TO 300])"
```

Example structure of indexer fields:
```
"indexer": {
      "config": {
        "indexer": {
          "arguments": {
            "fields": {
              "logo": {
                "options": {
                  "stats": {
                    "histogram": true
                  }
                },
                "paths": [
                  "site_map.searchables.*.video_tags.metadata_tags.*.metadata_tags.shot_tags.tags.text.Logo.text"
                ],
                "type": "text"
              },
              "title_type": {
                "options": {},
                "paths": [
                  "site_map.searchables.*.video_tags.metadata_tags.*.metadata_tags.shot_tags.tags.text.title"
                ],
                "type": "string"},
            }
          }
        }
      }
    }
```

Steps for updating index:

1. Edit content and save write_token
2. Call bitcode search_update
3. Finalize content

Search reference: https://github.com/qluvio/elv-search
